apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: websrver
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-empydir
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"  
      requests:
        cpu: 0.5
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-empydir
    emptyDir:
      sizeLimit: 256Mi
