apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /giropops1
      name: primeiro-empydir
    resources:
      limits:
        cpu: "2"
        memory: "128Mi"
      requests:
        cpu: 0.5
        memory: "64"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-empydir
    emptyDir:
      sizeLimit: 256Mi
